### ISSUE TITLE
 No such file or directory: '/home/ubuntu/FlowMaster/pools.yaml'

### ISSUE THREAD

**Issue by micweeks** [pavelmaksimov/FlowMaster#1]
Привет, очень хороший проект, однако столкнулся со следующей проблемой при устанвоке библиотеки

1) с ванильным python pip такого пакета вообще не видно
2) при установке через conda установка проходит замечательно, однако при запуске получаю

```
(base) ubuntu@primary:~/FlowMaster$ flowmaster run
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/bin/flowmaster", line 5, in <module>
    from flowmaster.__main__ import app
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/__main__.py", line 9, in <module>
    import flowmaster.cli.notebook
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/cli/notebook.py", line 5, in <module>
    from flowmaster.service import (
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/service.py", line 11, in <module>
    from flowmaster.operators.etl.policy import ETLNotebook
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/operators/etl/__init__.py", line 3, in <module>
    from flowmaster.operators.etl.providers.abstract import ProviderAbstract, ExportAbstract
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/operators/etl/providers/__init__.py", line 4, in <module>
    from flowmaster.operators.etl.providers.criteo import CriteoProvider
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/operators/etl/providers/criteo/__init__.py", line 2, in <module>
    from flowmaster.operators.etl.providers.criteo.export import (
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/operators/etl/providers/criteo/export.py", line 8, in <module>
    from flowmaster.executors import SleepIteration
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/executors/__init__.py", line 16, in <module>
    from flowmaster.pool import pools
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/pool.py", line 106, in <module>
    pools_dict = YamlHelper.parse_file(str(Settings.POOL_CONFIG_FILEPATH))
  File "/home/ubuntu/miniforge3/lib/python3.9/site-packages/flowmaster/utils/yaml_helper.py", line 14, in parse_file
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/FlowMaster/pools.yaml'
```

Что я делаю не так?(

**Comment by pavelmaksimov** [comment]
должен был создаться файл, но видимо, что-то пошло не так.
создай пустой файл в директории /home/ubuntu/FlowMaster/pools.yaml
